#!/bin/bash
#!/bin/bash 12-newest_files 13-unique 20-hiago 21-reverse 22-users_and_homes
#!/bin/bash 13-unique 20-hiago 21-reverse 22-users_and_homes
#!/bin/bash 20-hiago 21-reverse 22-users_and_homes
#!/bin/bash
#!/bin/bash 21-reverse 22-users_and_homes
#!/bin/bash 22-users_and_homes
#!/bin/bash
#!/bin/bash 7-file 8-cwd_state
#!/bin/bash 8-cwd_state 9-duplicate_last_line 10-no_more_js 11-directories 12-newest
#!/bin/bash 9-duplicate_last_line 10-no_more_js 11-directories 12-newest_files 13-unique 20-hiago 21-reverse 22-users_and_homes
#!/bin/bash 10-no_more_js 11-directories 12-newest_files 13-unique 20-hiago 21-reverse 22-users_and_homes
